<?php $_code=$this->getMethodCode() ?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <label for="<?php echo $_code ?>_check_no" class="required"><em>*</em><?php echo $this->__('fashioncheque Cardnumber') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Verification Code') ?>" class="input-text required-entry validate-digits validate-length maximum-length-19 minimum-length-19" id="<?php echo $_code ?>_card_no" name="payment[card_no]" value="<?php echo $this->htmlEscape($this->getInfoData('card_no')) ?>" maxlength="19" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_verificationcode" class="required"><em>*</em><?php echo $this->__('Verification Code') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Verification Code') ?>" class="input-text required-entry validate-digits maximum-length-6 minimum-length-6" id="<?php echo $_code ?>verificationcode" name="payment[verificationcode]" value="<?php echo $this->htmlEscape($this->getInfoData('verificationcode')) ?>" maxlength="6" />
        </div>
    </li>
    </ul>
</fieldset>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>